//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sakila
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sakilaEntities1 : DbContext
    {
        public sakilaEntities1()
            : base("name=sakilaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<rental> rental { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<store> store { get; set; }
    }
}
